### ISSUE TITLE
Enhancement: Add SignIn/SignUp with Google and Github

### ISSUE THREAD

**Issue by biresh1929** [AvgBlank/URLShortener#11]
Currently, the only way to sign in is by generating a user id and saving it for future login. I want to add OAuth Authentication for signing in through a Google account or a Github account.

Kindly assign me this
![trim-signin](https://github.com/user-attachments/assets/e24d2ba4-641a-4d67-a7c1-dd0071c161a7)

**Comment by AalokeCode** [comment]
Alright! You can work on it
