### ISSUE TITLE
Bug: Broken GitHub Account Link and Incorrect Timestamp Display

### ISSUE THREAD

**Issue by abhirajadhikary06** [AvgBlank/URLShortener#12]
@AalokeCode @AvgBlank 
I noticed that the GitHub account for AverageBlack is returning a 404 error, so it seems the link to the account is not provided properly . Additionally, there’s an issue with the timestamp for the creation of the link—it doesn’t appear to be displaying correctly.

_I also had a suggestion: it might improve usability if clicking on the trim.lol logo redirected users to the "generateurl" page. I think this would create a smoother navigation experience._

**Comment by AalokeCode** [comment]
Alright! You can work on it. Also, the suggestion seems good. So, you can add that as well

**Comment by abhirajadhikary06** [comment]
Can you assign this issue to me?
Looking forward to give you an early update.

**Comment by AvgBlank** [comment]
I've assigned this issue to you, also regarding the github account AverageBlank, that used to be my old account, it's now AvgBlank.
