### ISSUE TITLE
Enhancement: Delete URL Shortening History

### ISSUE THREAD

**Issue by NOOBMASTER-08** [AvgBlank/URLShortener#15]
This feature introduces the ability to _**delete URL shortening history**_, allowing users to manage their data more effectively. Users can now remove specific URL entries from their history or clear their entire shortening history as needed. This functionality is especially useful for maintaining privacy, reducing clutter, and keeping track of only relevant shortened URLs.

### USECASE OF THIS FEATURE

1. **Selective or Full Deletion**: Users can delete individual URL entries or clear the entire history with one action.
2. **Enhanced Privacy Control**: Offers users control over their data, supporting privacy and data management.
3. **Streamlined Interface**: Designed for easy access in the user interface to make history management quick and efficient.

![image](https://github.com/user-attachments/assets/a2fa9871-c47f-417b-bd78-df7cbf9dd498)
_

> As there is no option for deleting the history

_

**Comment by NOOBMASTER-08** [comment]
hey.. look at this feature i suggested, it would be fun to contribute it
please, assignee it to me @NOOBMASTER-08 

thank you. @AalokeCode @ubaidrmn @AvgBlank

**Comment by AvgBlank** [comment]
Hey! I like this idea; I've assigned this to you.

**Comment by NOOBMASTER-08** [comment]
have a look at it @AvgBlank

**Comment by NOOBMASTER-08** [comment]
@ubaidrmn @Veerhan-glitch @AalokeCode
