### ISSUE TITLE
Bug: Logo Visibility Enhancement in Desktop View

### ISSUE THREAD

**Issue by NOOBMASTER-08** [AvgBlank/URLShortener#16]
The Trim.lol logo isn't clearly visible in the desktop view due to insufficient contrast between the logo color and the background. Users may not recognize the branding immediately.
![Screenshot 2024-10-27 104008](https://github.com/user-attachments/assets/fbf08d18-0a7c-48a2-98d4-7e7696ede91d)
![Screenshot 2024-10-27 103659](https://github.com/user-attachments/assets/70bb6db1-8e04-4ccd-b25f-a9e72ce4b3f2)

### **Suggested Solution:**

1. Change the logo color to a lighter or more contrasting shade to improve visibility.
2. Position it slightly down.
3. Consider slightly increasing the logo size for better prominence.

**Comment by AvgBlank** [comment]
Hey! Yes, now that you mention it, on some devices the logo isn't visible. Do you want me to assign this issue to you?

**Comment by NOOBMASTER-08** [comment]
yes...assign it to me
@AvgBlank

**Comment by NOOBMASTER-08** [comment]
@AvgBlank bro...look at the PR for logo enhancement #21

**Comment by AvgBlank** [comment]
Hey! You closed the PR?
![image](https://github.com/user-attachments/assets/7012587e-e370-4390-97e6-531eee90181e)

**Comment by NOOBMASTER-08** [comment]
😅i am new in open source.....i deleted it by mistake. I will create a PR ASAP

**Comment by NOOBMASTER-08** [comment]
@AvgBlank I have created a pull request  #31  for the issue

**Comment by AvgBlank** [comment]
> 😅i am new in open source.....i deleted it by mistake. I will create a PR ASAP

No Problem!
