### ISSUE TITLE
Enhancement: Adding Sign up with google to Sign up and Login page

### ISSUE THREAD

**Issue by AalokeCode** [AvgBlank/URLShortener#19]
Currently there is only login button which does both login and signup. So this issue should separate them. If anybody interested to take up this issue. Comment below!

**Comment by AvgBlank** [comment]
To rephrase it, the `Login with Google` should anyway do both, but when the user clicks `signup`, it should give them an option to either `Generate a User ID` or `Sign up with Google`.

**Comment by KaroK365** [comment]
Can you assign it to me and elaborate the problem a bit more?? 😊

**Comment by AvgBlank** [comment]
Hey! So, when you go to https://trim.lol (this is the website for this project), you see three options `Log In`, `Sign Up` and `Login with Google`.
![image](https://github.com/user-attachments/assets/04f53e96-e1ee-4cf2-ab71-4ce974d10b2b)

Now, when the user clicks either Sign Up, or Login, it doesn't give them an option to `Login/SignUp with Google`. Basically, you have to implement these options. 
Let me know if you have any questions.
