### ISSUE TITLE
Enhancement: Docker Compose - Connect the docker MongoDB with the web app

### ISSUE THREAD

**Issue by mdrehan369** [AvgBlank/URLShortener#24]

**Comment by mdrehan369** [comment]
Assign this issue to me under hactoberfest 2024

**Comment by AvgBlank** [comment]
Hey! I'll assign this but, could you explain to me what exactly you are trying to improve?

**Comment by mdrehan369** [comment]
Actually whenever a developer tries to run your application using docker compose command, the two containers which are "web" and "database" should connect automatically. But the URL given for the docker database is incorrect. I would correct the URL so that whenever a developer uses docker compose bot the containers should connect automatically
