### ISSUE TITLE
Google Log In Server Error

### ISSUE THREAD

**Issue by SparshKhanna0001** [AvgBlank/URLShortener#35]
When the user Clicks on the login with Google option. It throws an internal server error.

To be specific:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by AvgBlank** [comment]
It seems to be working?
![image](https://github.com/user-attachments/assets/bb724531-64ea-47b4-8906-e818fc4b2daf)
